### PR TITLE
TECH-193: Prefill forms from employer profile, backfill employer profile from first application

### PR DESCRIPTION
**Pull request by strdavis**
This pull request implements the employer data prefill feature. Changes for this feature are as follows:

- [x] Prefill new applications using data from employer profile.
- [x] Prefill new claims using data from associated application form.
- [x] Backfill employer profile using data from the first application the employer submits.
- [x] Do not update employer profile from token on each login; just create the profile if it does not exist, allowing user to edit all fields.
- [x] Modify createEmployer() to create record only if one does not exist.
- [x] Refactor code for obtaining credentials for the two types of application form.
- [x] Modify province and workbc centre fields in Edit Profile dialog to conform with data formatting in forms.
- [x] Support removal of values from employer profile.
- [x] Implement field validation in Edit Profile dialog.

This pull request also implements several other minor fixes:
- [x] Add loading indicators to list aside
- [x] TECH-509: Activate loading indicator when loading or saving profile
- [x] TECH-519: Activate loading indicator when loading Share dialog and during Share operation
- [x] TECH-503: Don't cut off In Progress claim form header for IDIR users

This pull request also attempts to resolve the following issues. Must verify in dev since unable to reproduce precisely locally: 
- [x] TECH-506: Never render embedded form until div used to hide embedded form header is rendered
- [x] TECH-520: Correct whitespace in Edit Profile dialog

### CODE REVIEW

**Comment by npham49** [comment]
Preliminary tests on the autofilling, it does work on the application forms (have and need). Couple items to note:
- If the user put in a Phone number in the form XXXXXXXXXX instead of XXX-XXX-XXXX, and then save and then start a new form, the field is autofilled as "XXXXXXXXXX  " (two white spaces are added). And then when they return to the Admin Client, the 2 white spaces persists in the dialog.
- Similar issue for the Fax number if it is not in this form +XXXXXXXXXX.
- If a user inputs a number above 12 digits on Phone or Fax and then click save, the dialog would not react, nothing would happen, but on the API logs, it clearly states "value too long for type character(12)". I feel like there should be an error indicator on the dialog (useNotify might help?).
Will continue to test pre-fill based on first form submission.

**Comment by npham49** [comment]
Backfill data works, had an account with 1 submission and the employer data was filled correctly.

**Comment by npham49** [comment]
Tested the following 2 scenarios:
- test_ws: No applications. Account never had any pre-filled fields (except for the autogenerated name and email). Submitted a HaveEmployee and the dialog reflected properly, all the field are correctly filled based on the submitted application.
- elmsd_ws: Account had 1 application already submitted, employer record already had name, org name and email from previous run. Data did not pre-fill. One thing to note: I removed all fields to empty and saved, and then refreshed, show application, refresh, the profile is still empty, no pre-filling. Is this the intended result?

**Comment by npham49** [comment]
Tested the following scenario:
- elmsd_brian: 2 submitted application (1 in Submitted, 1 in Completed), data backfilled according to the first submitted application.

**Comment by strdavis** [comment]
> Preliminary tests on the autofilling, it does work on the application forms (have and need). Couple items to note:
> 
> * If the user put in a Phone number in the form XXXXXXXXXX instead of XXX-XXX-XXXX, and then save and then start a new form, the field is autofilled as "XXXXXXXXXX  " (two white spaces are added). And then when they return to the Admin Client, the 2 white spaces persists in the dialog.
> * Similar issue for the Fax number if it is not in this form +XXXXXXXXXX.
> * If a user inputs a number above 12 digits on Phone or Fax and then click save, the dialog would not react, nothing would happen, but on the API logs, it clearly states "value too long for type character(12)". I feel like there should be an error indicator on the dialog (useNotify might help?).
> 
> Will continue to test pre-fill based on first form submission.

Added validation to all fields in Edit Profile dialog, to conform with DB and with forms. Will also need to add validation to all application form fields that get backfilled into employer profile.

**Comment by strdavis** [comment]
> Tested the following 2 scenarios:
> 
> * test_ws: No applications. Account never had any pre-filled fields (except for the autogenerated name and email). Submitted a HaveEmployee and the dialog reflected properly, all the field are correctly filled based on the submitted application.
> * elmsd_ws: Account had 1 application already submitted, employer record already had name, org name and email from previous run. Data did not pre-fill. One thing to note: I removed all fields to empty and saved, and then refreshed, show application, refresh, the profile is still empty, no pre-filling. Is this the intended result?

This is the expected behaviour with the current implementation.

**Comment by strdavis** [comment]
> Tested the following scenario:
> 
> * elmsd_brian: 2 submitted application (1 in Submitted, 1 in Completed), data backfilled according to the first submitted application.

This is a bug, thanks for catching this! It was an error in the logic for detecting the first submission. I've implemented a fix for this.

**Comment by npham49** [comment]
Loading does occur in opening and closing for both Employer Dialog and Share Dialog, Loading Indicator spins accordingly.

**Comment by npham49** [comment]
Dialog validation works and prevents invalid inputs. Tested with numbers longer than 12 characters for Phone and Fax, form blocks accordingly. CRA number validation is a nice touch.

**Review by npham49 — APPROVED** [review]
> Tested the following scenario:
> 
> * elmsd_brian: 2 submitted application (1 in Submitted, 1 in Completed), data backfilled according to the first submitted application.

Reset DB to test first submission scenario, data backfilled is according to the first application submitted, overall function is working as intended!

**Pull request merged**
